. ~/.locate.zshrc
alias ariadone="~/Code/ariadone.py"
alias get="~/Code/clown/get.py"
alias pd="~/Code/playdelete.py"
alias ports="~/Code/ports.py"
alias tsplit="~/Code/tsplit.py"
alias txtnamer="~/Code/txtnamer.py"
alias vpn="~/Code/vpn.py"
alias x="~/Code/x.py"
