#! /bin/sh -e
# This file is automatically generated with: tup generate make.sh
export tup_vardict="$(cd $(dirname $0) && pwd)/tup-generate.vardict"
(nt2json vars.nt >vars.json)
(wheezy.template wezterm.lua.wz vars.json >wezterm.lua)
